export const UPDATE_ACCESS_TOKEN = "UPDATE_ACCESS_TOKEN";
export const RESET_USER_DATA = "RESET_USER_DATA";
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const GET_ITEM_BY_ID = "GET_ITEM_BY_ID";
export const GET_ALL_CARTS = "GET_ALL_CARTS";
export const REMOVE_UPDATE_CART_ITEM = "REMOVE_UPDATE_CART_ITEM";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ITEMS_BY_CATEGORY = "GET_ITEMS_BY_CATEGORY";
